Completed javascript-modal exercise - Francis Manalang
francismanalang/c0622-code-solutions pull request #45
Opened 2022-07-12 23:00 UTC by francismanalang

https://user-images.githubusercontent.com/101234537/178612485-e256c53a-0527-4f17-b536-05d6f465498f.mov

2022-07-13 16:40 UTC, codingcodymiller requested changes
How did you get your modal to overlay the content of the page? I don't see any use of the `position` property anywhere 🤔

2022-07-13 16:40 UTC, codingcodymiller commented on javascript-modal/main.js
> +var surveyToggle = true;
These variables never change in value and are only used to check if they have value in a conditional within a function, so they are unnecessary and should be deleted.

2022-07-13 20:22 UTC, francismanalang commented on javascript-modal/main.js
> +var surveyToggle = true;
https://user-images.githubusercontent.com/101234537/178827552-cdea16ec-bcce-4087-b7ac-2316453cb66a.mov

2022-07-14 18:48 UTC, codingcodymiller approved these changes

2022-07-15 22:26 UTC, merged